[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/503310378",
    "html_url": "https://github.com/jupyter/notebook/issues/4680#issuecomment-503310378",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4680",
    "id": 503310378,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwMzMxMDM3OA==",
    "user": {
      "login": "ssanderson",
      "id": 1588357,
      "node_id": "MDQ6VXNlcjE1ODgzNTc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1588357?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ssanderson",
      "html_url": "https://github.com/ssanderson",
      "followers_url": "https://api.github.com/users/ssanderson/followers",
      "following_url": "https://api.github.com/users/ssanderson/following{/other_user}",
      "gists_url": "https://api.github.com/users/ssanderson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ssanderson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ssanderson/subscriptions",
      "organizations_url": "https://api.github.com/users/ssanderson/orgs",
      "repos_url": "https://api.github.com/users/ssanderson/repos",
      "events_url": "https://api.github.com/users/ssanderson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ssanderson/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-06-18T21:01:49Z",
    "updated_at": "2019-06-18T21:01:49Z",
    "author_association": "CONTRIBUTOR",
    "body": "Switching to `~` fixes the issue for me locally: https://github.com/jupyter/notebook/pull/4681",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/503311422",
    "html_url": "https://github.com/jupyter/notebook/issues/4680#issuecomment-503311422",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4680",
    "id": 503311422,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwMzMxMTQyMg==",
    "user": {
      "login": "ssanderson",
      "id": 1588357,
      "node_id": "MDQ6VXNlcjE1ODgzNTc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1588357?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ssanderson",
      "html_url": "https://github.com/ssanderson",
      "followers_url": "https://api.github.com/users/ssanderson/followers",
      "following_url": "https://api.github.com/users/ssanderson/following{/other_user}",
      "gists_url": "https://api.github.com/users/ssanderson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ssanderson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ssanderson/subscriptions",
      "organizations_url": "https://api.github.com/users/ssanderson/orgs",
      "repos_url": "https://api.github.com/users/ssanderson/repos",
      "events_url": "https://api.github.com/users/ssanderson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ssanderson/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-06-18T21:04:58Z",
    "updated_at": "2019-06-18T21:04:58Z",
    "author_association": "CONTRIBUTOR",
    "body": "NOTE: Clearing your bower cache is required to reproduce this issue. If you've previously build the js dependencies successfully, bower appears to continue to re-use the old deps even though it resolves different versions with an empty cache. :(",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/503526593",
    "html_url": "https://github.com/jupyter/notebook/issues/4680#issuecomment-503526593",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4680",
    "id": 503526593,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwMzUyNjU5Mw==",
    "user": {
      "login": "leestott",
      "id": 2511341,
      "node_id": "MDQ6VXNlcjI1MTEzNDE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2511341?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/leestott",
      "html_url": "https://github.com/leestott",
      "followers_url": "https://api.github.com/users/leestott/followers",
      "following_url": "https://api.github.com/users/leestott/following{/other_user}",
      "gists_url": "https://api.github.com/users/leestott/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/leestott/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/leestott/subscriptions",
      "organizations_url": "https://api.github.com/users/leestott/orgs",
      "repos_url": "https://api.github.com/users/leestott/repos",
      "events_url": "https://api.github.com/users/leestott/events{/privacy}",
      "received_events_url": "https://api.github.com/users/leestott/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-06-19T11:46:52Z",
    "updated_at": "2019-06-19T11:46:52Z",
    "author_association": "NONE",
    "body": "Just as update this fixes build issues in Build Pipelines in Azure DevOps Pipelines we had  the following issues and Errors \r\n\r\n![image](https://user-images.githubusercontent.com/2511341/59762792-ed41c580-928f-11e9-987c-37eeb3c33282.png)\r\n\r\nError \r\n ##[section]Starting: Run base Tests\r\n==============================================================================\r\nTask         : Command line\r\nDescription  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows\r\nVersion      : 2.151.1\r\nAuthor       : Microsoft Corporation\r\nHelp         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line\r\n==============================================================================\r\nGenerating script.\r\n========================== Starting Command Output ===========================\r\n[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/0ec4b1f4-49ab-41ab-9b5f-a8215f60bf3e.sh\r\nAvailable kernels:\r\n  python3    /opt/hostedtoolcache/Python/3.6.8/x64/share/jupyter/kernels/python3\r\n\r\nTest group: base\r\nTest file: &#x2F;home&#x2F;vsts&#x2F;work&#x2F;1&#x2F;s&#x2F;notebook&#x2F;tests&#x2F;base&#x2F;highlight.js                 ‌\r\nPage Error\r\n  Message:   TypeError: undefined is not an object (evaluating 'e.createContext')\r\n  Call stack:\r\n    line 1 of static/components/preact-compat/index.js\r\n    line 1 of static/components/preact-compat/index.js\r\nPage Error\r\n  Message:   TypeError: undefined is not an object (evaluating 'e.createContext')\r\n  Call stack:\r\n    line 1 of static/components/preact-compat/index.js\r\n    line 1 of static/components/preact-compat/index.js\r\nPage Error\r\n  Message:   ReferenceError: Can't find variable: preactCompat\r\n  Call stack:\r\n    line 42225 of static/notebook/js/main.min.js\r\n    line 1693 of static/components/requirejs/require.js in execCb\r\n    line 881 of static/components/requirejs/require.js in check\r\n    line 1173 of static/components/requirejs/require.js in enable\r\n    line 1554 of static/components/requirejs/require.js in enable\r\n    line 1158 of static/components/requirejs/require.js\r\n    line 134 of static/components/requirejs/require.js\r\n    line 59 of static/components/requirejs/require.js in each\r\n    line 1110 of static/components/requirejs/require.js in enable\r\n    line 1554 of static/components/requirejs/require.js in enable\r\n    line 1158 of static/components/requirejs/require.js\r\n    line 134 of static/components/requirejs/require.js\r\n    line 59 of static/components/requirejs/require.js in each\r\n    line 1110 of static/components/requirejs/require.js in enable\r\n    line 786 of static/components/requirejs/require.js in init\r\n    line 1457 of static/components/requirejs/require.js\r\nTimeout for http://localhost:8888/a@b/\r\nIs the notebook server running?\r\n\r\nDetails for the 5 failed tests:\r\n\r\nIn /home/vsts/work/1/s/notebook/tests/base/highlight.js\r\n  Untitled suite in &#x2F;home&#x2F;vsts&#x2F;work&#x2F;1&#x2F;s&#x2F;notebook&#x2F;tests&#x2F;base&#x2F;highlight.js‌\r\n    uncaughtError: &quot;.CodeMirror-code&quot; still did not exist in 10000ms‌\r\nIn /home/vsts/work/1/s/notebook/tests/base/keyboard.js\r\n  Untitled suite in &#x2F;home&#x2F;vsts&#x2F;work&#x2F;1&#x2F;s&#x2F;notebook&#x2F;tests&#x2F;base&#x2F;keyboard.js‌\r\n    uncaughtError: &quot;.CodeMirror-code&quot; still did not exist in 10000ms‌\r\nIn /home/vsts/work/1/s/notebook/tests/base/misc.js\r\n  Untitled suite in &#x2F;home&#x2F;vsts&#x2F;work&#x2F;1&#x2F;s&#x2F;notebook&#x2F;tests&#x2F;base&#x2F;misc.js‌\r\n    uncaughtError: &quot;.CodeMirror-code&quot; still did not exist in 10000ms‌\r\nIn /home/vsts/work/1/s/notebook/tests/base/security.js\r\n  Untitled suite in &#x2F;home&#x2F;vsts&#x2F;work&#x2F;1&#x2F;s&#x2F;notebook&#x2F;tests&#x2F;base&#x2F;security.js‌\r\n    uncaughtError: &quot;.CodeMirror-code&quot; still did not exist in 10000ms‌\r\nIn /home/vsts/work/1/s/notebook/tests/base/utils.js\r\n  Untitled suite in &#x2F;home&#x2F;vsts&#x2F;work&#x2F;1&#x2F;s&#x2F;notebook&#x2F;tests&#x2F;base&#x2F;utils.js‌\r\n    uncaughtError: &quot;.CodeMirror-code&quot; still did not exist in 10000ms‌\r\nRunning tests with notebook directory '/tmp/tmpi8t4hukp'\r\n \r\n_______________________________",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/503574167",
    "html_url": "https://github.com/jupyter/notebook/issues/4680#issuecomment-503574167",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4680",
    "id": 503574167,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwMzU3NDE2Nw==",
    "user": {
      "login": "ssanderson",
      "id": 1588357,
      "node_id": "MDQ6VXNlcjE1ODgzNTc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1588357?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ssanderson",
      "html_url": "https://github.com/ssanderson",
      "followers_url": "https://api.github.com/users/ssanderson/followers",
      "following_url": "https://api.github.com/users/ssanderson/following{/other_user}",
      "gists_url": "https://api.github.com/users/ssanderson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ssanderson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ssanderson/subscriptions",
      "organizations_url": "https://api.github.com/users/ssanderson/orgs",
      "repos_url": "https://api.github.com/users/ssanderson/repos",
      "events_url": "https://api.github.com/users/ssanderson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ssanderson/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-06-19T14:01:49Z",
    "updated_at": "2019-06-19T14:01:49Z",
    "author_association": "CONTRIBUTOR",
    "body": "@gnestor @minrk looks like you two have most of the git history around managing these js dependencies. Any objection to switching to pinning preact and friends with `~` instead of `^`?",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/503642913",
    "html_url": "https://github.com/jupyter/notebook/issues/4680#issuecomment-503642913",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4680",
    "id": 503642913,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwMzY0MjkxMw==",
    "user": {
      "login": "gnestor",
      "id": 512354,
      "node_id": "MDQ6VXNlcjUxMjM1NA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/512354?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gnestor",
      "html_url": "https://github.com/gnestor",
      "followers_url": "https://api.github.com/users/gnestor/followers",
      "following_url": "https://api.github.com/users/gnestor/following{/other_user}",
      "gists_url": "https://api.github.com/users/gnestor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gnestor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gnestor/subscriptions",
      "organizations_url": "https://api.github.com/users/gnestor/orgs",
      "repos_url": "https://api.github.com/users/gnestor/repos",
      "events_url": "https://api.github.com/users/gnestor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gnestor/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-06-19T16:53:42Z",
    "updated_at": "2019-06-19T16:53:42Z",
    "author_association": "CONTRIBUTOR",
    "body": "No objection from me 👍 ",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/504097524",
    "html_url": "https://github.com/jupyter/notebook/issues/4680#issuecomment-504097524",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4680",
    "id": 504097524,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwNDA5NzUyNA==",
    "user": {
      "login": "ssanderson",
      "id": 1588357,
      "node_id": "MDQ6VXNlcjE1ODgzNTc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1588357?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ssanderson",
      "html_url": "https://github.com/ssanderson",
      "followers_url": "https://api.github.com/users/ssanderson/followers",
      "following_url": "https://api.github.com/users/ssanderson/following{/other_user}",
      "gists_url": "https://api.github.com/users/ssanderson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ssanderson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ssanderson/subscriptions",
      "organizations_url": "https://api.github.com/users/ssanderson/orgs",
      "repos_url": "https://api.github.com/users/ssanderson/repos",
      "events_url": "https://api.github.com/users/ssanderson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ssanderson/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-06-20T16:39:17Z",
    "updated_at": "2019-06-20T16:39:17Z",
    "author_association": "CONTRIBUTOR",
    "body": "@gnestor do you want to hit the button on https://github.com/jupyter/notebook/pull/4681 , or should we wait for more feedback? I'm a bit anxious to land this b/c as far as I can tell running the notebook from a fresh local checkout is broken right now.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/505154506",
    "html_url": "https://github.com/jupyter/notebook/issues/4680#issuecomment-505154506",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4680",
    "id": 505154506,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwNTE1NDUwNg==",
    "user": {
      "login": "gnestor",
      "id": 512354,
      "node_id": "MDQ6VXNlcjUxMjM1NA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/512354?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gnestor",
      "html_url": "https://github.com/gnestor",
      "followers_url": "https://api.github.com/users/gnestor/followers",
      "following_url": "https://api.github.com/users/gnestor/following{/other_user}",
      "gists_url": "https://api.github.com/users/gnestor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gnestor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gnestor/subscriptions",
      "organizations_url": "https://api.github.com/users/gnestor/orgs",
      "repos_url": "https://api.github.com/users/gnestor/repos",
      "events_url": "https://api.github.com/users/gnestor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gnestor/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-06-24T19:51:48Z",
    "updated_at": "2019-06-24T19:51:48Z",
    "author_association": "CONTRIBUTOR",
    "body": "> If I clear my ~/.cache/bower and then run python setup.py css js in an editably-installed notebook repo, when I run jupyter notebook I get a blank page on the notebook page, with console errors about missing createContext from preact-compat\r\n\r\n@ssanderson I'm unable to reproduce this. ",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/505174158",
    "html_url": "https://github.com/jupyter/notebook/issues/4680#issuecomment-505174158",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4680",
    "id": 505174158,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwNTE3NDE1OA==",
    "user": {
      "login": "ssanderson",
      "id": 1588357,
      "node_id": "MDQ6VXNlcjE1ODgzNTc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1588357?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ssanderson",
      "html_url": "https://github.com/ssanderson",
      "followers_url": "https://api.github.com/users/ssanderson/followers",
      "following_url": "https://api.github.com/users/ssanderson/following{/other_user}",
      "gists_url": "https://api.github.com/users/ssanderson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ssanderson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ssanderson/subscriptions",
      "organizations_url": "https://api.github.com/users/ssanderson/orgs",
      "repos_url": "https://api.github.com/users/ssanderson/repos",
      "events_url": "https://api.github.com/users/ssanderson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ssanderson/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-06-24T20:45:56Z",
    "updated_at": "2019-06-24T20:45:56Z",
    "author_association": "CONTRIBUTOR",
    "body": "@gnestor hmm, interesting. What OS are you on? Your cache path might be different than mine.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/505174260",
    "html_url": "https://github.com/jupyter/notebook/issues/4680#issuecomment-505174260",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4680",
    "id": 505174260,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwNTE3NDI2MA==",
    "user": {
      "login": "ssanderson",
      "id": 1588357,
      "node_id": "MDQ6VXNlcjE1ODgzNTc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1588357?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ssanderson",
      "html_url": "https://github.com/ssanderson",
      "followers_url": "https://api.github.com/users/ssanderson/followers",
      "following_url": "https://api.github.com/users/ssanderson/following{/other_user}",
      "gists_url": "https://api.github.com/users/ssanderson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ssanderson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ssanderson/subscriptions",
      "organizations_url": "https://api.github.com/users/ssanderson/orgs",
      "repos_url": "https://api.github.com/users/ssanderson/repos",
      "events_url": "https://api.github.com/users/ssanderson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ssanderson/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-06-24T20:46:13Z",
    "updated_at": "2019-06-24T20:46:13Z",
    "author_association": "CONTRIBUTOR",
    "body": "(I'm on Ubuntu 18.04)",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/505270182",
    "html_url": "https://github.com/jupyter/notebook/issues/4680#issuecomment-505270182",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4680",
    "id": 505270182,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwNTI3MDE4Mg==",
    "user": {
      "login": "gnestor",
      "id": 512354,
      "node_id": "MDQ6VXNlcjUxMjM1NA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/512354?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gnestor",
      "html_url": "https://github.com/gnestor",
      "followers_url": "https://api.github.com/users/gnestor/followers",
      "following_url": "https://api.github.com/users/gnestor/following{/other_user}",
      "gists_url": "https://api.github.com/users/gnestor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gnestor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gnestor/subscriptions",
      "organizations_url": "https://api.github.com/users/gnestor/orgs",
      "repos_url": "https://api.github.com/users/gnestor/repos",
      "events_url": "https://api.github.com/users/gnestor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gnestor/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-06-25T03:46:44Z",
    "updated_at": "2019-06-25T03:46:44Z",
    "author_association": "CONTRIBUTOR",
    "body": "I'm on macOS 10.14.5. I was able to `rm -rf ~/.cache/bower` and reinstall the notebook but I'm not seeing these errors. ",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/505338482",
    "html_url": "https://github.com/jupyter/notebook/issues/4680#issuecomment-505338482",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4680",
    "id": 505338482,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwNTMzODQ4Mg==",
    "user": {
      "login": "limbuu",
      "id": 22807324,
      "node_id": "MDQ6VXNlcjIyODA3MzI0",
      "avatar_url": "https://avatars.githubusercontent.com/u/22807324?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/limbuu",
      "html_url": "https://github.com/limbuu",
      "followers_url": "https://api.github.com/users/limbuu/followers",
      "following_url": "https://api.github.com/users/limbuu/following{/other_user}",
      "gists_url": "https://api.github.com/users/limbuu/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/limbuu/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/limbuu/subscriptions",
      "organizations_url": "https://api.github.com/users/limbuu/orgs",
      "repos_url": "https://api.github.com/users/limbuu/repos",
      "events_url": "https://api.github.com/users/limbuu/events{/privacy}",
      "received_events_url": "https://api.github.com/users/limbuu/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-06-25T08:15:29Z",
    "updated_at": "2019-06-25T08:16:38Z",
    "author_association": "NONE",
    "body": "i am having same issue. Any fixes so far?\r\n![image](https://user-images.githubusercontent.com/22807324/60081540-b0734400-9751-11e9-84b5-7dfc6c48c410.png)\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/505511210",
    "html_url": "https://github.com/jupyter/notebook/issues/4680#issuecomment-505511210",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4680",
    "id": 505511210,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwNTUxMTIxMA==",
    "user": {
      "login": "ssanderson",
      "id": 1588357,
      "node_id": "MDQ6VXNlcjE1ODgzNTc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1588357?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ssanderson",
      "html_url": "https://github.com/ssanderson",
      "followers_url": "https://api.github.com/users/ssanderson/followers",
      "following_url": "https://api.github.com/users/ssanderson/following{/other_user}",
      "gists_url": "https://api.github.com/users/ssanderson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ssanderson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ssanderson/subscriptions",
      "organizations_url": "https://api.github.com/users/ssanderson/orgs",
      "repos_url": "https://api.github.com/users/ssanderson/repos",
      "events_url": "https://api.github.com/users/ssanderson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ssanderson/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-06-25T16:03:29Z",
    "updated_at": "2019-06-25T16:04:07Z",
    "author_association": "CONTRIBUTOR",
    "body": "@limbuu I think this should be fixed on head of master since @lresende merged https://github.com/jupyter/notebook/pull/4681. You'll need to `rm -rf notebook/static/components` in your git checkout and then re-run `python setup.py js css` to fix your bad javascript install.\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/505513518",
    "html_url": "https://github.com/jupyter/notebook/issues/4680#issuecomment-505513518",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4680",
    "id": 505513518,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwNTUxMzUxOA==",
    "user": {
      "login": "ssanderson",
      "id": 1588357,
      "node_id": "MDQ6VXNlcjE1ODgzNTc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1588357?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ssanderson",
      "html_url": "https://github.com/ssanderson",
      "followers_url": "https://api.github.com/users/ssanderson/followers",
      "following_url": "https://api.github.com/users/ssanderson/following{/other_user}",
      "gists_url": "https://api.github.com/users/ssanderson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ssanderson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ssanderson/subscriptions",
      "organizations_url": "https://api.github.com/users/ssanderson/orgs",
      "repos_url": "https://api.github.com/users/ssanderson/repos",
      "events_url": "https://api.github.com/users/ssanderson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ssanderson/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-06-25T16:08:58Z",
    "updated_at": "2019-06-25T16:08:58Z",
    "author_association": "CONTRIBUTOR",
    "body": "\r\n@gnestor have you cleared out your previous install of the js/css components in the repo? The components installed by `bower install` are downloaded to `notebook/static/components` (that directory is gitignored so it won't look dirty), so if you've previously set up the notebook in your checkout, you've probably already got them.\r\n\r\nFor me a complete repro is:\r\n\r\n```\r\n# Alternatively, `rm -rf notebook/static/components`.\r\n$ git clone git@github.com:jupyter/notebook.git\r\n$ cd notebook/\r\n# Last commit prior to fix being merged.\r\n$ git checkout fc2c46141deb06b9e939b295ce254907830d3147\r\n\r\n# Assuming this is where your bower cache is.\r\n$ rm -rf ~/.cache/bower/\r\n\r\n# Install in fresh venv. `pip install -e .` invokes setup.py js internally, which uses bower to\r\n# download to notebook/static/components.\r\n$ mkvirtualenv -p python3 nb-repro\r\n$ pip install -e .\r\n\r\n$ jupyter notebook\r\n\r\n# Navigate to new notebook page\r\n```\r\n\r\n![image](https://user-images.githubusercontent.com/1588357/60114481-e8728b00-9741-11e9-8c4d-e71df28bf6ca.png)\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/505513717",
    "html_url": "https://github.com/jupyter/notebook/issues/4680#issuecomment-505513717",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4680",
    "id": 505513717,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwNTUxMzcxNw==",
    "user": {
      "login": "ssanderson",
      "id": 1588357,
      "node_id": "MDQ6VXNlcjE1ODgzNTc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1588357?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ssanderson",
      "html_url": "https://github.com/ssanderson",
      "followers_url": "https://api.github.com/users/ssanderson/followers",
      "following_url": "https://api.github.com/users/ssanderson/following{/other_user}",
      "gists_url": "https://api.github.com/users/ssanderson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ssanderson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ssanderson/subscriptions",
      "organizations_url": "https://api.github.com/users/ssanderson/orgs",
      "repos_url": "https://api.github.com/users/ssanderson/repos",
      "events_url": "https://api.github.com/users/ssanderson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ssanderson/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-06-25T16:09:31Z",
    "updated_at": "2019-06-25T16:09:31Z",
    "author_association": "CONTRIBUTOR",
    "body": "Also worth noting: this is only broken on the notebook page itself. The notebook list page is fine.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/506425778",
    "html_url": "https://github.com/jupyter/notebook/issues/4680#issuecomment-506425778",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4680",
    "id": 506425778,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwNjQyNTc3OA==",
    "user": {
      "login": "gnestor",
      "id": 512354,
      "node_id": "MDQ6VXNlcjUxMjM1NA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/512354?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gnestor",
      "html_url": "https://github.com/gnestor",
      "followers_url": "https://api.github.com/users/gnestor/followers",
      "following_url": "https://api.github.com/users/gnestor/following{/other_user}",
      "gists_url": "https://api.github.com/users/gnestor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gnestor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gnestor/subscriptions",
      "organizations_url": "https://api.github.com/users/gnestor/orgs",
      "repos_url": "https://api.github.com/users/gnestor/repos",
      "events_url": "https://api.github.com/users/gnestor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gnestor/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-06-27T16:50:27Z",
    "updated_at": "2019-06-27T16:50:27Z",
    "author_association": "CONTRIBUTOR",
    "body": "@ssanderson I ended up just replacing preact with react in notebook. The ended up using preact only because of react's PATENT issue a couple years back. Next, I'd like to get react working with requirejs vs. adding a global UMD script to the page.",
    "performed_via_github_app": null
  }
]
