[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/204751566",
    "html_url": "https://github.com/jupyter/notebook/pull/1288#issuecomment-204751566",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/1288",
    "id": 204751566,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIwNDc1MTU2Ng==",
    "user": {
      "login": "bschwb",
      "id": 7480477,
      "node_id": "MDQ6VXNlcjc0ODA0Nzc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7480477?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bschwb",
      "html_url": "https://github.com/bschwb",
      "followers_url": "https://api.github.com/users/bschwb/followers",
      "following_url": "https://api.github.com/users/bschwb/following{/other_user}",
      "gists_url": "https://api.github.com/users/bschwb/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bschwb/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bschwb/subscriptions",
      "organizations_url": "https://api.github.com/users/bschwb/orgs",
      "repos_url": "https://api.github.com/users/bschwb/repos",
      "events_url": "https://api.github.com/users/bschwb/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bschwb/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-02T16:24:21Z",
    "updated_at": "2016-04-02T16:24:21Z",
    "author_association": "CONTRIBUTOR",
    "body": "With this fix the notebook is rendered correctly.\nMy test doesn't pass though.\n\nI'm unsure if the test is coded correctly.\nAfter the kernel is killed, the correct html would be rendered.\nSo maybe I misunderstood something with asynchrony when calling `this.evaluate()`.\n\nI also tried to debug like it's described here:\nhttps://drupalize.me/blog/201410/using-remote-debugger-casperjs-and-phantomjs\nBut I can't set breakpoints in functions which are passed to `this.evaluate()`.\n\nAny help is appreciated.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/204763407",
    "html_url": "https://github.com/jupyter/notebook/pull/1288#issuecomment-204763407",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/1288",
    "id": 204763407,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIwNDc2MzQwNw==",
    "user": {
      "login": "willingc",
      "id": 2680980,
      "node_id": "MDQ6VXNlcjI2ODA5ODA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2680980?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/willingc",
      "html_url": "https://github.com/willingc",
      "followers_url": "https://api.github.com/users/willingc/followers",
      "following_url": "https://api.github.com/users/willingc/following{/other_user}",
      "gists_url": "https://api.github.com/users/willingc/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/willingc/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/willingc/subscriptions",
      "organizations_url": "https://api.github.com/users/willingc/orgs",
      "repos_url": "https://api.github.com/users/willingc/repos",
      "events_url": "https://api.github.com/users/willingc/events{/privacy}",
      "received_events_url": "https://api.github.com/users/willingc/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-02T17:32:30Z",
    "updated_at": "2016-04-02T17:32:30Z",
    "author_association": "MEMBER",
    "body": "@BerndSchwarzenbacher I've restarted the Travis tests since the Travis may have timed out on the tests and reported a false failure. I will leave it to @Carreau to review the PR contents.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/207043316",
    "html_url": "https://github.com/jupyter/notebook/pull/1288#issuecomment-207043316",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/1288",
    "id": 207043316,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIwNzA0MzMxNg==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-07T18:40:05Z",
    "updated_at": "2016-04-07T18:40:05Z",
    "author_association": "MEMBER",
    "body": "@BerndSchwarzenbacher I think your code all right, but your test is running afoul of async rendering of markdown. I'll write up how to reliably wait for the rendered result.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/207055513",
    "html_url": "https://github.com/jupyter/notebook/pull/1288#issuecomment-207055513",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/1288",
    "id": 207055513,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIwNzA1NTUxMw==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-07T19:18:03Z",
    "updated_at": "2016-04-07T19:18:03Z",
    "author_association": "MEMBER",
    "body": "@BerndSchwarzenbacher I made https://github.com/BerndSchwarzenbacher/notebook/pull/1 which adds the necessary async waits to your tests. The casper async testing stuff is far from obvious.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/207085170",
    "html_url": "https://github.com/jupyter/notebook/pull/1288#issuecomment-207085170",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/1288",
    "id": 207085170,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIwNzA4NTE3MA==",
    "user": {
      "login": "bschwb",
      "id": 7480477,
      "node_id": "MDQ6VXNlcjc0ODA0Nzc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7480477?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bschwb",
      "html_url": "https://github.com/bschwb",
      "followers_url": "https://api.github.com/users/bschwb/followers",
      "following_url": "https://api.github.com/users/bschwb/following{/other_user}",
      "gists_url": "https://api.github.com/users/bschwb/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bschwb/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bschwb/subscriptions",
      "organizations_url": "https://api.github.com/users/bschwb/orgs",
      "repos_url": "https://api.github.com/users/bschwb/repos",
      "events_url": "https://api.github.com/users/bschwb/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bschwb/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-07T20:59:49Z",
    "updated_at": "2016-04-07T20:59:49Z",
    "author_association": "CONTRIBUTOR",
    "body": "@minrk Thanks a lot for your help!\nI added logging of the error and I had a look at the source of `CodeMirror.getMode`. It seems to me, that it actually never returns an empty object. So we might delete the extra `if (!mode)` case.\nWhat do you think?\n",
    "performed_via_github_app": null
  }
]
